### ISSUE TITLE
Code for Sakaguchi & Van Durme 2018 not on the site

### ISSUE THREAD

**Issue by dmhowcroft** [decompositional-semantics-initiative/decompositional-semantics-initiative.github.io#19]
Page 209 (second page of the PDF) of [Sakaguchi & Van Durme (2018)](https://www.aclweb.org/anthology/P18-1020/) says that the code for EASL will be available at "decomp.net", which redirects to [decomp.io](http://decomp.io/).

Is the Decompositional Semantics Initiative website the same one that this paper was linking to?

If so, is the code available somewhere on the website and I was just failing to find it?

Thank you for any help you can offer!

**Comment by keisks** [comment]
Hi, thank you for reaching out!
The EASL code is available at https://github.com/decomp-sem/EASL

**Comment by dmhowcroft** [comment]
Thank you!
